version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: itrader
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:root@postgres:5432/itrader
      REDIS_URL: redis://redis:6379
      RUST_LOG: info,itrader_backend=debug
      JWT_SECRET: ${JWT_SECRET:-your-jwt-secret-key}
      ADMIN_TOKEN: ${ADMIN_TOKEN:-dev-token-123}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY:-your-openrouter-api-key}
      EMAIL_ADDRESS: ${EMAIL_ADDRESS:-}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD:-}
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./db:/app/db
      - ./data:/app/data
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: