version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: itrader_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  bot:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres/itrader_db
      REDIS_URL: redis://redis:6379
      RUST_LOG: info,itrader_backend=debug
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      EMAIL_ADDRESS: ${EMAIL_ADDRESS}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    volumes:
      - ./config:/app/config
      - ./test_data:/app/test_data
    ports:
      - "8080:8080"
      - "9090:9090"  # Metrics

volumes:
  postgres_data: